/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PortalDriverRouteImport } from './routes/portal.driver'
import { Route as PortalAgentRouteImport } from './routes/portal.agent'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTerminalRouteImport } from './routes/app.terminal'
import { Route as AppSalesRouteImport } from './routes/app.sales'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppDriversRouteImport } from './routes/app.drivers'
import { Route as AppCommissionsRouteImport } from './routes/app.commissions'
import { Route as AppBranchesRouteImport } from './routes/app.branches'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppSalesIdRouteImport } from './routes/app.sales.$id'
import { Route as AppDriversIdRouteImport } from './routes/app.drivers.$id'
import { Route as AppAgentsIdRouteImport } from './routes/app.agents.$id'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PortalDriverRoute = PortalDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAgentRoute = PortalAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => PortalRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalRoute = AppTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIdRoute = AppSalesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppDriversIdRoute = AppDriversIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDriversRoute,
} as any)
const AppAgentsIdRoute = AppAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/drivers': typeof AppDriversRouteWithChildren
  '/app/pos': typeof AppPosRoute
  '/app/sales': typeof AppSalesRouteWithChildren
  '/app/terminal': typeof AppTerminalRoute
  '/app/users': typeof AppUsersRoute
  '/portal/agent': typeof PortalAgentRoute
  '/portal/driver': typeof PortalDriverRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/drivers/$id': typeof AppDriversIdRoute
  '/app/sales/$id': typeof AppSalesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/drivers': typeof AppDriversRouteWithChildren
  '/app/pos': typeof AppPosRoute
  '/app/sales': typeof AppSalesRouteWithChildren
  '/app/terminal': typeof AppTerminalRoute
  '/app/users': typeof AppUsersRoute
  '/portal/agent': typeof PortalAgentRoute
  '/portal/driver': typeof PortalDriverRoute
  '/app': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/drivers/$id': typeof AppDriversIdRoute
  '/app/sales/$id': typeof AppSalesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/drivers': typeof AppDriversRouteWithChildren
  '/app/pos': typeof AppPosRoute
  '/app/sales': typeof AppSalesRouteWithChildren
  '/app/terminal': typeof AppTerminalRoute
  '/app/users': typeof AppUsersRoute
  '/portal/agent': typeof PortalAgentRoute
  '/portal/driver': typeof PortalDriverRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/drivers/$id': typeof AppDriversIdRoute
  '/app/sales/$id': typeof AppSalesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/portal'
    | '/app/agents'
    | '/app/audit'
    | '/app/branches'
    | '/app/commissions'
    | '/app/drivers'
    | '/app/pos'
    | '/app/sales'
    | '/app/terminal'
    | '/app/users'
    | '/portal/agent'
    | '/portal/driver'
    | '/app/'
    | '/app/agents/$id'
    | '/app/drivers/$id'
    | '/app/sales/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/app/agents'
    | '/app/audit'
    | '/app/branches'
    | '/app/commissions'
    | '/app/drivers'
    | '/app/pos'
    | '/app/sales'
    | '/app/terminal'
    | '/app/users'
    | '/portal/agent'
    | '/portal/driver'
    | '/app'
    | '/app/agents/$id'
    | '/app/drivers/$id'
    | '/app/sales/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/portal'
    | '/app/agents'
    | '/app/audit'
    | '/app/branches'
    | '/app/commissions'
    | '/app/drivers'
    | '/app/pos'
    | '/app/sales'
    | '/app/terminal'
    | '/app/users'
    | '/portal/agent'
    | '/portal/driver'
    | '/app/'
    | '/app/agents/$id'
    | '/app/drivers/$id'
    | '/app/sales/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/driver': {
      id: '/portal/driver'
      path: '/driver'
      fullPath: '/portal/driver'
      preLoaderRoute: typeof PortalDriverRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/agent': {
      id: '/portal/agent'
      path: '/agent'
      fullPath: '/portal/agent'
      preLoaderRoute: typeof PortalAgentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/terminal': {
      id: '/app/terminal'
      path: '/terminal'
      fullPath: '/app/terminal'
      preLoaderRoute: typeof AppTerminalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drivers': {
      id: '/app/drivers'
      path: '/drivers'
      fullPath: '/app/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commissions': {
      id: '/app/commissions'
      path: '/commissions'
      fullPath: '/app/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branches': {
      id: '/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/$id': {
      id: '/app/sales/$id'
      path: '/$id'
      fullPath: '/app/sales/$id'
      preLoaderRoute: typeof AppSalesIdRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/app/drivers/$id': {
      id: '/app/drivers/$id'
      path: '/$id'
      fullPath: '/app/drivers/$id'
      preLoaderRoute: typeof AppDriversIdRouteImport
      parentRoute: typeof AppDriversRoute
    }
    '/app/agents/$id': {
      id: '/app/agents/$id'
      path: '/$id'
      fullPath: '/app/agents/$id'
      preLoaderRoute: typeof AppAgentsIdRouteImport
      parentRoute: typeof AppAgentsRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsIdRoute: typeof AppAgentsIdRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsIdRoute: AppAgentsIdRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppDriversRouteChildren {
  AppDriversIdRoute: typeof AppDriversIdRoute
}

const AppDriversRouteChildren: AppDriversRouteChildren = {
  AppDriversIdRoute: AppDriversIdRoute,
}

const AppDriversRouteWithChildren = AppDriversRoute._addFileChildren(
  AppDriversRouteChildren,
)

interface AppSalesRouteChildren {
  AppSalesIdRoute: typeof AppSalesIdRoute
}

const AppSalesRouteChildren: AppSalesRouteChildren = {
  AppSalesIdRoute: AppSalesIdRoute,
}

const AppSalesRouteWithChildren = AppSalesRoute._addFileChildren(
  AppSalesRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppAuditRoute: typeof AppAuditRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppDriversRoute: typeof AppDriversRouteWithChildren
  AppPosRoute: typeof AppPosRoute
  AppSalesRoute: typeof AppSalesRouteWithChildren
  AppTerminalRoute: typeof AppTerminalRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppAuditRoute: AppAuditRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppDriversRoute: AppDriversRouteWithChildren,
  AppPosRoute: AppPosRoute,
  AppSalesRoute: AppSalesRouteWithChildren,
  AppTerminalRoute: AppTerminalRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalAgentRoute: typeof PortalAgentRoute
  PortalDriverRoute: typeof PortalDriverRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAgentRoute: PortalAgentRoute,
  PortalDriverRoute: PortalDriverRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
